<a href="https://colab.research.google.com/github/PrasoonPratham/Kaggle/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Using the Kaggle API to fetch the dataset for this competition

!pip install kaggle
api_token = {"username":"prathamprasoon","key":"4eec6bdf09208b0e38d6f39fcec31bde"}
import json
import zipfile
import os
!mkdir /root/.kaggle
!echo '{"username":"USERNAME","key":"API_KEY"}' > /root/.kaggle/kaggle.json
with open('/root/.kaggle/kaggle.json', 'w') as file:
    json.dump(api_token, file)
!kaggle competitions download -c titanic

mkdir: cannot create directory ‘/root/.kaggle’: File exists
train.csv: Skipping, found more recently modified local copy (use --force to force download)
test.csv: Skipping, found more recently modified local copy (use --force to force download)
gender_submission.csv: Skipping, found more recently modified local copy (use --force to force download)


In [2]:
import pandas as pd

train_data = pd.read_csv("/content/train.csv")

In [3]:
train_data["Age"].fillna(train_data["Age"].median(), inplace = True)

In [4]:
train_data

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [5]:
labels = train_data['Survived']
train_data["Sex"].replace({"male": 1, "female":0}, inplace=True)
trainDataR = train_data.drop(["Survived","Ticket","Cabin","Name","PassengerId","Embarked"], axis=1).values

In [6]:
trainDataR

array([[ 3.    ,  1.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  0.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 3.    ,  0.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 3.    ,  0.    , 28.    ,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 3.    ,  1.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [7]:
from sklearn.model_selection import train_test_split
trainData, trainLabels , valData, valLabels = (train_test_split(trainDataR, labels,train_size=0.76))

In [9]:
from sklearn import tree

decision_tree = tree.DecisionTreeClassifier(max_depth = 3)
trainData = trainData.astype(float) 
trainLabels = trainLabels.astype(float) 

In [10]:
trainLabels

array([[  2.    ,   0.    ,  50.    ,   0.    ,   1.    ,  26.    ],
       [  3.    ,   1.    ,  30.    ,   0.    ,   0.    ,   7.225 ],
       [  3.    ,   0.    ,  29.    ,   0.    ,   4.    ,  21.075 ],
       ...,
       [  3.    ,   0.    ,  28.    ,   0.    ,   0.    ,   8.1375],
       [  3.    ,   0.    ,  24.    ,   0.    ,   0.    ,   8.85  ],
       [  1.    ,   1.    ,  58.    ,   0.    ,   2.    , 113.275 ]])

In [11]:
model = decision_tree.fit(trainData, valData)

In [12]:
accuracy = model.score(trainLabels, valLabels) * 100
accuracy

82.2429906542056

In [14]:
test_data = pd.read_csv("/content/test.csv")

In [17]:
import numpy as np



test_data["Sex"].replace({"male": 1, "female":0}, inplace=True)
test_data["Age"].fillna(test_data["Age"].median(), inplace = True)
test_data["Pclass"].fillna(test_data["Pclass"].median(), inplace = True)
test_data["Fare"].fillna(test_data["Fare"].median(), inplace = True)


testDataR = test_data.drop(["Ticket","Cabin","Name","PassengerId","Embarked"], axis=1).values
testDataR = testDataR.astype(np.float64)

In [18]:
testDataR

array([[ 3.        ,  1.        , 34.5       ,  0.        ,  0.        ,
         7.8292    ],
       [ 3.        ,  0.        , 47.        ,  1.        ,  0.        ,
         7.        ],
       [ 2.        ,  1.        , 62.        ,  0.        ,  0.        ,
         9.6875    ],
       ...,
       [ 3.        ,  1.        , 38.5       ,  0.        ,  0.        ,
         7.25      ],
       [ 3.        ,  1.        , 30.27259036,  0.        ,  0.        ,
         8.05      ],
       [ 3.        ,  1.        , 30.27259036,  1.        ,  1.        ,
        22.3583    ]])

In [19]:

testDataR = testDataR.astype(float)
pred = model.predict(testDataR)
pred = pred.astype(np.int16)

In [20]:
submission = pd.read_csv('/content/gender_submission.csv')
submission['Survived'] = pred
submission.to_csv('submission.csv', index=False)

In [21]:
submission.head()


PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1