<a href="https://colab.research.google.com/github/PrasoonPratham/Kaggle/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Using the Kaggle API to fetch the dataset for this competition

!pip install kaggle
api_token = {}
import json
import zipfile
import os
!mkdir /root/.kaggle
!echo '{"username":"USERNAME","key":"API_KEY"}' > /root/.kaggle/kaggle.json
with open('/root/.kaggle/kaggle.json', 'w') as file:
    json.dump(api_token, file)
!kaggle competitions download -c titanic

  0% 0.00/28.0k [00:00<?, ?B/s]
100% 28.0k/28.0k [00:00<00:00, 39.4MB/s]
  0% 0.00/3.18k [00:00<?, ?B/s]
100% 3.18k/3.18k [00:00<00:00, 3.54MB/s]
  0% 0.00/59.8k [00:00<?, ?B/s]
100% 59.8k/59.8k [00:00<00:00, 64.3MB/s]


In [15]:
import pandas as pd

train_data = pd.read_csv("/content/train.csv")

In [16]:
train_data["Age"].fillna("30", inplace = True)

In [32]:
train_data

PassengerId  Survived  Pclass  ...     Fare Cabin Embarked
0              1         0       3  ...   7.2500   NaN        S
1              2         1       1  ...  71.2833   C85        C
2              3         1       3  ...   7.9250   NaN        S
3              4         1       1  ...  53.1000  C123        S
4              5         0       3  ...   8.0500   NaN        S
..           ...       ...     ...  ...      ...   ...      ...
886          887         0       2  ...  13.0000   NaN        S
887          888         1       1  ...  30.0000   B42        S
888          889         0       3  ...  23.4500   NaN        S
889          890         1       1  ...  30.0000  C148        C
890          891         0       3  ...   7.7500   NaN        Q

[891 rows x 12 columns]

In [36]:
labels = train_data['Survived']
train_data["Sex"].replace({"male": 1, "female":0}, inplace=True)
trainDataR = train_data.drop(["Survived","Ticket","Cabin","Name","PassengerId","Embarked"], axis=1).values

In [37]:
trainDataR

array([[3, 1, 22.0, 1, 0, 7.25],
       [1, 0, 38.0, 1, 0, 71.2833],
       [3, 0, 26.0, 0, 0, 7.925],
       ...,
       [3, 0, '30', 1, 2, 23.45],
       [1, 1, 26.0, 0, 0, 30.0],
       [3, 1, 32.0, 0, 0, 7.75]], dtype=object)

In [38]:
from sklearn.model_selection import train_test_split
trainData, trainLabels , valData, valLabels = (train_test_split(trainDataR, labels,train_size=0.75))

In [45]:
from sklearn import tree

decision_tree = tree.DecisionTreeClassifier(max_depth = 3)
trainData = trainData.astype(float) 
trainLabels = trainLabels.astype(float) 

In [48]:
trainLabels

array([[ 3.    ,  1.    , 30.    ,  1.    ,  1.    , 15.2458],
       [ 1.    ,  1.    , 65.    ,  0.    ,  0.    , 26.55  ],
       [ 2.    ,  1.    , 34.    ,  0.    ,  0.    , 13.    ],
       ...,
       [ 1.    ,  1.    , 27.    ,  1.    ,  0.    , 53.1   ],
       [ 1.    ,  1.    , 54.    ,  0.    ,  0.    , 51.8625],
       [ 1.    ,  0.    , 26.    ,  0.    ,  0.    , 78.85  ]])

In [49]:
model = decision_tree.fit(trainData, valData)

In [51]:
accuracy = model.score(trainLabels, valLabels) * 100
accuracy

80.26905829596413

In [70]:
test_data

PassengerId  Pclass  ... Cabin  Embarked
0            892       3  ...   NaN         Q
1            893       3  ...   NaN         S
2            894       2  ...   NaN         Q
3            895       3  ...   NaN         S
4            896       3  ...   NaN         S
..           ...     ...  ...   ...       ...
413         1305       3  ...   NaN         S
414         1306       1  ...  C105         C
415         1307       3  ...   NaN         S
416         1308       3  ...   NaN         S
417         1309       3  ...   NaN         C

[418 rows x 11 columns]

In [93]:
test_data = pd.read_csv("/content/test.csv")



test_data["Sex"].replace({"male": 1, "female":0}, inplace=True)
test_data["Age"].fillna("30", inplace = True)
test_data["Pclass"].fillna("2", inplace = True)
test_data["Fare"].fillna("8", inplace = True)


testDataR = test_data.drop(["Ticket","Cabin","Name","PassengerId","Embarked"], axis=1).values
testDataR = testDataR.astype(np.float64)

# import numpy as np
# np.any(np.isnan(trainDataR,dtype=float))
# trainDataR.replace(nan,0)


In [94]:
testDataR

array([[ 3.    ,  1.    , 34.5   ,  0.    ,  0.    ,  7.8292],
       [ 3.    ,  0.    , 47.    ,  1.    ,  0.    ,  7.    ],
       [ 2.    ,  1.    , 62.    ,  0.    ,  0.    ,  9.6875],
       ...,
       [ 3.    ,  1.    , 38.5   ,  0.    ,  0.    ,  7.25  ],
       [ 3.    ,  1.    , 30.    ,  0.    ,  0.    ,  8.05  ],
       [ 3.    ,  1.    , 30.    ,  1.    ,  1.    , 22.3583]])

In [95]:

testDataR = testDataR.astype(float)
pred = model.predict(testDataR)
pred = pred.astype(np.int16)

In [97]:
submission = pd.read_csv('/content/gender_submission.csv')
submission['Survived'] = pred
submission.to_csv('submission.csv', index=False)

In [98]:
submission.head()


PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1